# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import network_pb2 as network__pb2


class NetworkTrafficStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamNetworkInfo = channel.stream_stream(
                '/network.NetworkTraffic/StreamNetworkInfo',
                request_serializer=network__pb2.NetworkRequest.SerializeToString,
                response_deserializer=network__pb2.NetworkResponse.FromString,
                )


class NetworkTrafficServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamNetworkInfo(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NetworkTrafficServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamNetworkInfo': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamNetworkInfo,
                    request_deserializer=network__pb2.NetworkRequest.FromString,
                    response_serializer=network__pb2.NetworkResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'network.NetworkTraffic', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NetworkTraffic(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamNetworkInfo(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/network.NetworkTraffic/StreamNetworkInfo',
            network__pb2.NetworkRequest.SerializeToString,
            network__pb2.NetworkResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
