# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: network.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rnetwork.proto\x12\x07network\"\x10\n\x0eNetworkRequest\"=\n\x0fNetworkResponse\x12\x17\n\x0f\x63urrent_traffic\x18\x01 \x01(\x05\x12\x11\n\tbandwidth\x18\x02 \x01(\x05\x32^\n\x0eNetworkTraffic\x12L\n\x11StreamNetworkInfo\x12\x17.network.NetworkRequest\x1a\x18.network.NetworkResponse\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'network_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_NETWORKREQUEST']._serialized_start=26
  _globals['_NETWORKREQUEST']._serialized_end=42
  _globals['_NETWORKRESPONSE']._serialized_start=44
  _globals['_NETWORKRESPONSE']._serialized_end=105
  _globals['_NETWORKTRAFFIC']._serialized_start=107
  _globals['_NETWORKTRAFFIC']._serialized_end=201
# @@protoc_insertion_point(module_scope)
