# Verwende das offizielle Python-Image als Basis
FROM python:3.8-slim

# Setze das Arbeitsverzeichnis innerhalb des Containers
WORKDIR /app

# Kopiere die Anwendungsdateien in das Arbeitsverzeichnis
COPY . /app

# Installiere die Abhängigkeiten
RUN pip install --no-cache-dir -r requirements.txt

# Setze den Befehl, der beim Start des Containers ausgeführt wird
CMD ["python", "streamer.py"]
