# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: location.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0elocation.proto\x12\x08location\"L\n\x0cLocationInfo\x12\x18\n\x10\x63urrent_datetime\x18\x01 \x01(\t\x12\x10\n\x08timezone\x18\x02 \x01(\t\x12\x10\n\x08location\x18\x03 \x01(\t\"T\n\x14LocationInfoResponse\x12\x18\n\x10\x63urrent_datetime\x18\x01 \x01(\t\x12\x10\n\x08timezone\x18\x02 \x01(\t\x12\x10\n\x08location\x18\x03 \x01(\t2f\n\x10LocationStreamer\x12R\n\x12StreamLocationInfo\x12\x16.location.LocationInfo\x1a\x1e.location.LocationInfoResponse\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'location_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LOCATIONINFO']._serialized_start=28
  _globals['_LOCATIONINFO']._serialized_end=104
  _globals['_LOCATIONINFORESPONSE']._serialized_start=106
  _globals['_LOCATIONINFORESPONSE']._serialized_end=190
  _globals['_LOCATIONSTREAMER']._serialized_start=192
  _globals['_LOCATIONSTREAMER']._serialized_end=294
# @@protoc_insertion_point(module_scope)
